export const LOGIN="LOGIN";
export const SIGNUP="SIGNUP";
export const SIGNOUT="SIGNOUT";
export const SET_USER_INFO="SET_USER_INFO";
export const LOGIN_FAILED="LOGIN_FAILED";
export const SIGNUP_FAILED="SIGNUP_FAILED";
export const UPDATE_PROFILE="UPDATE_PROFILE";

export const OPEN_LOGIN_FORM="OPEN_LOGIN_FORM";
export const CLOSE_LOGIN_FORM="CLOSE_LOGIN_FORM";
export const OPEN_EDIT_ITEM_FORM="OPEN_EDIT_ITEM_FORM";
export const CLOSE_EDIT_ITEM_FORM="CLOSE_EDIT_ITEM_FORM";
export const OPEN_EDIT_PROFILE_FORM="OPEN_EDIT_PROFILE_FORM";
export const CLOSE_EDIT_PROFILE_FORM="CLOSE_EDIT_PROFILE_FORM";
export const OPEN_CART_PAGE="OPEN_CART_PAGE";
export const CLOSE_CART_PAGE="CLOSE_CART_PAGE";
export const OPEN_MESSAGE="OPEN_MESSAGE";
export const CLOSE_MESSAGE="CLOSE_MESSAGE";
export const OPEN_ERROR_MESSAGE="OPEN_ERROR_MESSAGE";
export const CLOSE_ERROR_MESSAGE="CLOSE_ERROR_MESSAGE";
export const START_LOADING="START_LOADING";
export const STOP_LOADING="STOP_LOADING";

export const ADD_CARD = "ADD_CARD";
export const ADD_CARD_TO_THE_DECK = "ADD_CARD_TO_THE_DECK";
export const SET_USER_DECK = "SET_USER_DECK";
export const SET_BOOK_CARDS = "SET_BOOK_CARDS";
export const SET_CHEAPEST_CARDS = "SET_CHEAPEST_CARDS";
export const DELETE_CARD = "DELETE_CARD";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";